### ISSUE TITLE
Same namespace than upstream? 

### ISSUE THREAD

**Issue by alexisLefebvre** [cerad/FOSUserBundle3#3]
Will this fork use the same namespace? If this has to be changed because of Composer, does it mean that it won't be able to merge this to upstream later?

**Comment by ahundiak** [comment]
I would not anticipate changing any namespaces so, in theory, merging upstream would not be a problem.

**Comment by alexisLefebvre** [comment]
I was thinking about Packagist but after consideration, there's no reason that Composer or Packagist require the namespace to be consistent with the repository name/URL. So it should be possible to replace a package with a fork in `composer.json` even if the same namespace is used in the Bundle. You can close this question if you think there won't be any problem.

**Comment by alexisLefebvre** [comment]
I just saw you were not planning to publish a fork, I'm closing this issue. Sorry for the inconvenience.
